- README.md
- code/logic/fossil/_common/platform.h
- meson.build
Resolving issues found from C++ side from platform utilities.
> Patch update to resolve an issue found from C++

- .github/workflows/meson_ci.yml
- code/logic/fossil/test/benchmark.h
- code/logic/fossil/test/framework.h
- code/logic/fossil/test/mockup.h
- code/logic/fossil/test/unittest.h
- code/tests/cases/test_bdd.c
- code/tests/cases/test_bdd.cpp
- code/tests/cases/test_sample.c
- code/tests/cases/test_sample.cpp
- code/tests/cases/test_tdd.c
- code/tests/cases/test_tdd.cpp
- code/tests/meson.build
- code/tests/tools/generate-runner.py
- code/tests/unit_runner.cpp
Restructured test bed to include a new test runner for C++ side of the API, moved test case files into a new directory `cases` to avoid cluttering the main `tests` directory, updated `generate-runner.py` to account for both C and C++.
Same cases, one set for C and a new set for C++
> Mixed lang testbed

- code/logic/fossil/test/assume.h
- code/tests/cases/test_bdd.cpp
- code/tests/cases/test_mark.cpp
- code/tests/cases/test_tdd.cpp
This pull request is for C string assumptions to have the ability to work with C++ STL strings
Same test cases but changed the C++ versions of test cases that where previously classic C string with STL string to ensure this worked not just on paper.
> Pull request for C String assumptions to work with C++ STL string

- .github/ciimage/Dockerfile.archlinux
- .github/ciimage/Dockerfile.debian
- .github/ciimage/Dockerfile.fedora
- .github/ciimage/Dockerfile.ubuntu
- .github/workflows/meson_ci.yml
- code/logic/fossil/test/testing.h
- code/logic/testing.c
In this PR I have added timeout to ensure test cases run at a respectful rate, fixed time for the runner so it can calculate time using start and end time, plus updated messages to include more dynamic messaging and a new set for timeouts.
Same test cases to ensure nothing broke, but do need to update Debian Docker image file due to malfunction.
> Pull Request add timeout and fix time

- code/logic/fossil/test/assume.h
- code/tests/cases/test_tdd.c
- code/tests/cases/test_tdd.cpp
In the interest of simplifying the assertion string list byte strings will be removed due to extra trouble and cost to manage
Same test but no byte string assertions in site
> Remove byte string assertions

- README.md
- code/logic/fossil/test/testing.h
- code/logic/testing.c
- meson.build
This PR allows Fossil Test to scan assertions within a given test case to ensure that no test case goes without an assertion.
Same test cases to ensure nothing broke
> Pull Request Scan Assertions

- README.md
- code/logic/fossil/test/marking.h
- code/logic/fossil/test/testing.h
- code/logic/testing.c
- meson.build
This Pull Request allows assertions to perform anomaly detection and to determine if a given assertion has been given the role as the goat for most copy pasted assertion.
Same test cases to ensure all is good.
> Pull Request Updating Assertions

- code/logic/testing.c
Doing a clean up for the Fossil Test source, managed to minimize TUI output calls to print functions and add more null checking.
Same test as before to ensure nothing broke.
> PR cleanup code

- README.md
- code/logic/fossil/test/testing.h
- code/logic/testing.c
- meson.build
Nothing complex beyond the addition of a dry run command.
Same test as before.
> Pull Request for Dry Run

- .github/workflows/meson_ci.yml
- Dockerfile
- code/logic/fossil/test/marking.h
- code/logic/fossil/test/mocking.h
- code/logic/fossil/test/testing.h
- code/logic/marking.c
- code/logic/mocking.c
- code/logic/testing.c
- code/tests/cases/test_mock.c
- code/tests/cases/test_mock.cpp
Changed custom type names to follow existing custom type patterns for the current project, making use of standard int library for holding values in these custom types, gave better names to functions, bumped response up to 50, removed version of these responses using emojis for consistency.
> Cleaning and refactoring source files

- code/logic/fossil/test/mocking.h
- code/logic/mocking.c
Cleaning up the mock file pair before adding new features
Same test.
> Clean mock

- code/logic/fossil/test/testing.h
- code/logic/testing.c
Updated the summary for the Pizza Test to provide a more dynamic output and insightful introspection.
Same test
> Add NLP and dynamic summary

- code/logic/fossil/test/internal.h
- code/logic/fossil/test/testing.h
- code/logic/testing.c
The beginning of the integration of Jellyfish AI began, first of many challenges the summary now has intelligence for analysis, predicting probability, exact percentage of success, and average rate of the test results.
Additionally smart commentary and suggestions are added to provide more character. Time based analysis calculates the anomalies.
New jellyfish AI components being added over time, Fossil Test will be smarter over time.
Same test under newly drafted prototypes.
> Fossil Test and the dawn of Jellyfish AI integrations

- README.md
- code/logic/common.c
- code/logic/fossil/pizza/assume.h
- code/logic/fossil/pizza/common.h
- code/logic/fossil/pizza/test.h
- code/logic/test.c
- code/tests/cases/test_mark.c
- code/tests/cases/test_mark.cpp
- code/tests/cases/test_tdd.c
- code/tests/cases/test_tdd.cpp
This PR add more test cases to cover new assumptions for soap, char, memory and more, not only that cases have been added for mark as will.
Last notable change is that now assume will display both the variable name and value stored in variable to better inform the tester about the failed result and avoid the black box issue.
New test cases for new assumptions and new cases for benchmark.
> Adding Test & Apply Change to Assume

- README.md
- code/logic/common.c
- code/logic/fossil/pizza/common.h
- code/logic/test.c
Provide a way to toggle timeout value with the new timeout command which takes the in a number as seconds, set as 60 seconds by default.
Same test.
> Add timeout command

- README.md
- code/logic/common.c
Added new --options flags to some sub-commands `filter`, `sort`, `shuffle` to better show the valid options for sub-flag configurations.
Same test.
> Added --options flags

- README.md
- code/logic/common.c
- code/logic/fossil/pizza/common.h
- code/logic/test.c
After a while I added a generic skip flag to allow one to skip test cases from execution, this would be handy for rooting out flaky cases.
Via manual command-line testing
> Added skip flags

- README.md
- code/logic/common.c
- meson.build
Updating version info to reflect the next milestone release.
N/A
> updating to version 1.2.2

- code/logic/common.c
- code/logic/fossil/pizza/common.h
The Pizza Test framework has been updated to include extended system metadata under its info flag, offering deeper contextual awareness for each test run. New metafields now providing detailed kernel-level information. Additional descriptors such as **Codename** (`Linux`), **Description** (`GNU/Linux`), **Vendor** (`debian`), and **Family** (`Unix`) establish a clear identity of the operating system environment. These are complemented by broader classifications like **Type** (`Desktop/Server`), **Platform** (`linux`), and **Machine** (`aarch64`), enabling the framework to better contextualize results and support platform-specific diagnostics or configuration handling in heterogeneous environments.
Same test
This project is licensed under the Mozilla Public License - see the …
> Adding host metadata

- code/logic/fossil/pizza/test.h
Reworking this part to be minimized and to be better
> Reworking messagef

- .github/workflows/conan_ci.yml
- .github/workflows/container_ci.yml
- Dockerfile
- README.md
> Testing Docker archive system
